// Auto-generated by scripts/extract_calls.py — do not edit by hand.
const CALLS_DATA = [
  {
    "id": "transcript0",
    "recording_file": "recording0.mp3",
    "transcript_file": "transcript0.txt",
    "hospital": "Dr. Ishan Shah - Invictus Gastro Hospital",
    "phone": "+917879278795",
    "call_date": "2026-09-15",
    "call_time": "17:55",
    "call_datetime_display": "Sep 15, 2026 5:55 PM",
    "duration": "2:28",
    "duration_seconds": 148,
    "outcome": "Success",
    "caller_name": "Shivam",
    "patient_name": null,
    "city": "Ahmedabad",
    "department": "Abdominal Pain Evaluation",
    "doctor": "Dr. Ishan Shah",
    "first_visit": null,
    "appointment_booked": true,
    "appointment_date": "2026-09-16",
    "appointment_time": "11:00",
    "appointment_datetime_display": "Sep 16, 2026 11:00 AM",
    "languages": [
      "Gujarati",
      "English"
    ],
    "topics": [
      "Treatments offered",
      "Stomach pain (2 days)",
      "Appointment booking",
      "OPD timings",
      "Clinic address"
    ],
    "summary": "Shivam asked what treatments the clinic offers and described 2 days of stomach pain. The agent explained Dr. Ishan Shah's GI surgery specialties (gallbladder stones, hernia, piles, liver/pancreas, laparoscopic and bariatric surgery) and recommended a consultation to diagnose the cause. He booked a consultation for the next morning at 11:00 AM and was given the Invictus Hospital (Nikol) address."
  },
  {
    "id": "transcript1",
    "recording_file": "recording1.mp3",
    "transcript_file": "transcript1.txt",
    "hospital": "Dr. Ishan Shah - Invictus Gastro Hospital",
    "phone": "+917879278795",
    "call_date": "2026-09-15",
    "call_time": "19:39",
    "call_datetime_display": "Sep 15, 2026 7:39 PM",
    "duration": "2:33",
    "duration_seconds": 153,
    "outcome": "Success",
    "caller_name": "Shivam",
    "patient_name": null,
    "city": "Ahmedabad",
    "department": "Intestinal Disorder Treatment",
    "doctor": "Dr. Ishan Shah",
    "first_visit": true,
    "appointment_booked": true,
    "appointment_date": "2026-09-16",
    "appointment_time": "16:00",
    "appointment_datetime_display": "Sep 16, 2026 04:00 PM",
    "languages": [
      "Gujarati",
      "English"
    ],
    "topics": [
      "Doctor's qualifications",
      "Intestinal problem (2 months)",
      "Prior endoscopy",
      "Appointment booking",
      "OPD timings"
    ],
    "summary": "Shivam, a first-time caller, asked about Dr. Ishan Shah's qualifications, then described a 2-month-old intestinal problem that hadn't improved despite a prior endoscopy. The agent explained that whether medicine or surgery was needed could only be confirmed after evaluation, and booked a first-visit consultation for the next evening at 4:00 PM."
  },
  {
    "id": "transcript2",
    "recording_file": "recording2.mp3",
    "transcript_file": "transcript2.txt",
    "hospital": "Dr. Ishan Shah - Invictus Gastro Hospital",
    "phone": "+917879278795",
    "call_date": "2026-09-16",
    "call_time": "08:51",
    "call_datetime_display": "Sep 16, 2026 8:51 AM",
    "duration": "2:33",
    "duration_seconds": 153,
    "outcome": "Success",
    "caller_name": "Rahul",
    "patient_name": null,
    "city": "Ahmedabad",
    "department": "Abdominal Pain & Fever Evaluation",
    "doctor": "Dr. Ishan Shah",
    "first_visit": true,
    "appointment_booked": true,
    "appointment_date": "2026-09-17",
    "appointment_time": "16:00",
    "appointment_datetime_display": "Sep 17, 2026 04:00 PM",
    "languages": [
      "Gujarati",
      "English"
    ],
    "topics": [
      "Treatments offered",
      "Abdominal pain with fever (3-4 days)",
      "Appointment booking",
      "OPD timings",
      "Clinic address"
    ],
    "summary": "Rahul, a first-time caller, asked about the clinic's treatments before describing 3-4 days of abdominal pain accompanied by mild fever. The agent recommended a consultation with Dr. Ishan Shah for a proper evaluation and booked one for the next day at 4:00 PM, providing the Invictus Hospital (Nikol) address."
  },
  {
    "id": "transcript3",
    "recording_file": "recording3.mp3",
    "transcript_file": "transcript3.txt",
    "hospital": "Dr. Ishan Shah - Invictus Gastro Hospital",
    "phone": "+917879278795",
    "call_date": "2026-09-16",
    "call_time": "09:24",
    "call_datetime_display": "Sep 16, 2026 9:24 AM",
    "duration": "2:00",
    "duration_seconds": 120,
    "outcome": "Success",
    "caller_name": "Rahul",
    "patient_name": null,
    "city": "Ahmedabad",
    "department": "Vomiting / GI Symptom Evaluation",
    "doctor": "Dr. Ishan Shah",
    "first_visit": true,
    "appointment_booked": true,
    "appointment_date": "2026-09-17",
    "appointment_time": "15:00",
    "appointment_datetime_display": "Sep 17, 2026 03:00 PM",
    "languages": [
      "Gujarati"
    ],
    "topics": [
      "Appointment booking",
      "Vomiting (4 days)",
      "OPD timings"
    ],
    "summary": "Rahul, a first-time caller, reported 4 days of vomiting with no prior tests done. The agent booked a consultation for the next afternoon (Sep 17) at 3:00 PM, noted his name and contact number, and confirmed the team would follow up to reconfirm the slot."
  }
];
